# Домашнее задание 2 (5 баллов).

Все задания ниже имеют равный вес (5/16).

In [42]:
import pandas as pd

In [43]:
import os

In [45]:
!wget https://github.com/hse-ds/iad-intro-ds/raw/master/2023/homeworks/Data.zip
!unzip /content/Data.zip

--2024-02-07 17:56:46--  https://github.com/hse-ds/iad-intro-ds/raw/master/2023/homeworks/Data.zip
Resolving github.com (github.com)... 140.82.121.4
Connecting to github.com (github.com)|140.82.121.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/hse-ds/iad-intro-ds/master/2023/homeworks/Data.zip [following]
--2024-02-07 17:56:46--  https://raw.githubusercontent.com/hse-ds/iad-intro-ds/master/2023/homeworks/Data.zip
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.108.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 16727 (16K) [application/zip]
Saving to: ‘Data.zip’

Data.zip            100%[===================>]  16.33K  --.-KB/s    in 0s

2024-02-07 17:56:46 (121 MB/s) - ‘Data.zip’ saved [16727/16727]

Archive:  /content/Data.zip
   creating: Data/
  inflating: Data/Students_info_0.csv
  inflating: Data/Students_info_1.csv
  inflating: Data/Students_info_2.csv
  inflating: Data/Students_info_3.csv
  inflating: Data/Students_info_4.csv
  inflating: Data/Students_info_5.csv
  inflating: Data/Students_info_6.csv
  inflating: Data/Students_info_7.csv
  inflating: Data/Students_info_8.csv
  inflating: Data/Students_info_9.csv
  inflating: Data/Students_marks_0.csv
  inflating: Data/Students_marks_1.csv
  inflating: Data/Students_marks_2.csv
  inflating: Data/Students_marks_3.csv
  inflating: Data/Students_marks_4.csv
  inflating: Data/Students_marks_5.csv
  inflating: Data/Students_marks_6.csv
  inflating: Data/Students_marks_7.csv
  inflating: Data/Students_marks_8.csv
  inflating: Data/Students_marks_9.csv

#### Описание данных

В папке Dat (https://github.com/hse-ds/iad-intro-ds/blob/master/2023/homeworks/Data.zip) находится информация о студентах. Всего 10 групп студентов. Файлы делятся на две категории:
    * Students_info_i - информация о студентах из группы i
    * Students_marks_i - оценки студентов из группы i за экзамены

### Одно из важных достоинств pandas $-$ это удобные методы реляционного взаимодействия с данными, аналогичные, например, возможностям SQL для слияния и конкатенации таблиц: merge, join, concat. Наличие готовых методов позволяет не реализовывать самостоятельно поэлементную обработку данных и оперировать сразу целыми таблицами данных.

Подробно об этих методах посмотрите тут: https://www.kaggle.com/residentmario/renaming-and-combining#Combining

#### Задание 1. Соберите всю информацию о студентах в одну таблицу df. В получившейся таблице должна быть информация и оценки всех студентов из всех групп. Напечатайте несколько строк таблицы для демонстрации результата.¶

In [51]:
# Путь к разархивированной папке с данными
path = '/content/Data'

# Создание DataFrame для хранения общей таблицы, таблиц с информацией, оценками
df = pd.DataFrame()
df_info = pd.DataFrame()
df_marks = pd.DataFrame()

# Получаем список файлов внутри папки
file_list = sorted(os.listdir(path))
# print(file_list)
for file in file_list:
    data = pd.read_csv(f"/content/Data/{file}")
    if file.startswith('Students_info'):
        # Объединение информационных таблиц в одну
        df_info = pd.concat([df_info, data])
    else:
        # Объединение таблиц с оценками в одну
        df_marks = pd.concat([df_marks, data])


df = pd.merge(df_info, df_marks, on='index', how='left')
df.head(10)

,index,gender,race/ethnicity,parental level of education,lunch,test preparation course,group,math score,reading score,writing score
0,0,female,group B,bachelor's degree,standard,none,group1,72,72,74
1,1,female,group C,some college,standard,completed,group1,69,90,88
2,2,female,group B,master's degree,standard,none,group1,90,95,93
3,3,male,group A,associate's degree,free/reduced,none,group1,47,57,44
4,4,male,group C,some college,standard,none,group1,76,78,75
5,5,female,group B,associate's degree,standard,none,group1,71,83,78
6,6,female,group B,some college,standard,completed,group1,88,95,92
7,7,male,group B,some college,free/reduced,none,group1,40,43,39
8,8,male,group D,high school,free/reduced,completed,group1,64,64,67
9,9,female,group B,high school,free/reduced,none,group1,38,60,50

#### Задание 2. Удалите столбец index у полученной таблицы. Напечатайте первые 10 строк таблицы.

In [52]:
df = df.drop('index', axis=1)
df.head(10)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,group,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,group1,72,72,74
1,female,group C,some college,standard,completed,group1,69,90,88
2,female,group B,master's degree,standard,none,group1,90,95,93
3,male,group A,associate's degree,free/reduced,none,group1,47,57,44
4,male,group C,some college,standard,none,group1,76,78,75
5,female,group B,associate's degree,standard,none,group1,71,83,78
6,female,group B,some college,standard,completed,group1,88,95,92
7,male,group B,some college,free/reduced,none,group1,40,43,39
8,male,group D,high school,free/reduced,completed,group1,64,64,67
9,female,group B,high school,free/reduced,none,group1,38,60,50

#### Задание 3. Выведите на экран размеры полученной таблицы

In [53]:
df.shape

(1000, 9)

#### Задание 4. Выведите на экран статистические характеристики числовых столбцов таблицы (минимум, максимум, среднее значение, стандартное отклонение)

In [54]:
# Список вызываемых методов
list_methods = ['min', 'max', 'mean', 'std']
# Выбор числовых столбцов и агрегация по списку методов
print(df.select_dtypes(include='number').agg(list_methods))

      math score  reading score  writing score
min      0.00000      17.000000      10.000000
max    100.00000     100.000000     100.000000
mean    66.08900      69.169000      68.054000
std     15.16308      14.600192      15.195657

#### Задание 5. Проверьте, есть ли в таблице пропущенные значения

In [56]:
# Поиск пропущенных значений по полям таблицы и их суммирование (0 - нет пропущенных значений в поле)
df.isnull().sum()

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
group                          0
math score                     0
reading score                  0
writing score                  0
dtype: int64

#### Задание 6. Выведите на экран средние баллы студентов по каждому предмету (math, reading, writing)

In [59]:
# df.select_dtypes(include='number').mean() - в случае, если в таблице имеются другие числовые поля
df[['math score', 'reading score', 'writing score']].mean()

math score       66.089
reading score    69.169
writing score    68.054
dtype: float64

**Задание 7. Как зависят оценки от того, проходил ли студент курс для подготовки к сдаче экзамена (test preparation course)? Выведите на экран для каждого предмета в отдельности средний балл студентов, проходивших курс для подготовки к экзамену и не проходивших курс.**

In [60]:
# Группировка по столбцу 'test preparation course'
gr_df = df.groupby('test preparation course')
# apply - добавление характеристики среднего балла по предмету к датасету
gr_df.apply(lambda x: x.select_dtypes(include='number').mean())

                         math score  reading score  writing score
test preparation course
completed                 69.695531      73.893855      74.418994
none                      64.077882      66.534268      64.504673

**Задание 8. Выведите на экран все различные значения из столбца lunch.**

In [62]:
print(df['lunch'].unique())

['standard' 'free/reduced']

**Задание 9. Переименуйте колонку "parental level of education" в "education", а "test preparation course" в "test preparation" с помощью метода pandas rename**
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.rename.html

In [63]:
df = df.rename(columns={"parental level of education":"education", "test preparation course":"test preparation"})
df

,gender,race/ethnicity,education,lunch,test preparation,group,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,group1,72,72,74
1,female,group C,some college,standard,completed,group1,69,90,88
2,female,group B,master's degree,standard,none,group1,90,95,93
3,male,group A,associate's degree,free/reduced,none,group1,47,57,44
4,male,group C,some college,standard,none,group1,76,78,75
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,group10,88,99,95
996,male,group C,high school,free/reduced,none,group10,62,55,55
997,female,group C,high school,free/reduced,completed,group10,59,71,65
998,female,group D,some college,standard,completed,group10,68,78,77
999,female,group D,some college,free/reduced,none,group10,77,86,86

**Зафиксируем минимальный балл для сдачи экзамена**

In [64]:
passmark = 50

**Задание 10. Ответьте на вопросы:**
    * Какая доля студентов сдала экзамен по математике (passmark >= 50)?
    * Какая доля студентов, проходивших курс подготовки к экзамену, сдала экзамен по математике?
    * Какая доля женщин, не проходивших курс подготовки к экзамену, не сдала экзамен по математике?

In [66]:
# Создание булевой серии и подсчёт частного от деления количества True на длину серии (подсчёт доли через mean())
(df['math score'] >= passmark).mean()

0.865

In [68]:
# Доступ к строкам df на основе логического выражения прохождения курса
df_comp = df.loc[df['test preparation'] == 'completed']
# Создание булевой серии и подсчёт доли
print((df_comp['math score'] >= passmark).mean())

0.9217877094972067

In [69]:
# Доступ к строкам df на основе логического выражения (женщина, курс не пройден)
df_female_none = df.loc[(df['test preparation'] == 'none') & (df['gender'] == 'female')]
# Создание булевой серии и подсчёт доли
print((df_female_none['math score'] < passmark).mean())

0.20958083832335328

**Задание 11. С помощью groupby выполните задания ниже. Также выведите время выполнения каждого из заданий.**
    * Для каждой этнической группы выведите средний балл за экзамен по чтению
    * Для каждого уровня образования выведите минимальный балл за экзамен по письму

In [70]:
%%time
df.groupby("race/ethnicity")["reading score"].mean()

CPU times: user 2.3 ms, sys: 19 µs, total: 2.31 ms
Wall time: 2.26 ms

race/ethnicity
group A    64.674157
group B    67.352632
group C    69.103448
group D    70.030534
group E    73.028571
Name: reading score, dtype: float64

In [71]:
%%time
df.groupby("education")["writing score"].min()

CPU times: user 3.49 ms, sys: 0 ns, total: 3.49 ms
Wall time: 3.18 ms

education
associate's degree    35
bachelor's degree     38
high school           15
master's degree       46
some college          19
some high school      10
Name: writing score, dtype: int64

**Задание 12. Выполните задание 11 с помощью циклов. Сравните время выполнения.**

In [72]:
%%time
for race in df['race/ethnicity'].unique():
    print(f"{race} {df[df['race/ethnicity'] == race]['reading score'].mean()}")

group B 67.35263157894737
group C 69.10344827586206
group A 64.67415730337079
group D 70.03053435114504
group E 73.02857142857142
CPU times: user 8.97 ms, sys: 2.07 ms, total: 11 ms
Wall time: 12.4 ms

In [73]:
%%time
for level in df['education'].unique():
    print(f"{level} {df[df['education'] == level]['writing score'].min()}")

bachelor's degree 38
some college 19
master's degree 46
associate's degree 35
high school 15
some high school 10
CPU times: user 11.2 ms, sys: 0 ns, total: 11.2 ms
Wall time: 16.5 ms

__Ответ__: Время выполнения через циклы намного больше, чем через группировку pandas. Эффективнее применять последний метод.

**Задание 13. Выведите на экран средние баллы студентов по каждому предмету в зависимости от пола и уровня образования. То есть должно получиться количество групп, равных 2 * (число уровней образования), и для каждой такой группы выыведите средний балл по каждому из предметов.**

Это можно сделать с помощью сводных таблиц (pivot_table):

https://www.kaggle.com/kamilpolak/tutorial-how-to-use-pivot-table-in-pandas

In [74]:
pd.pivot_table(df, index=['gender', 'education'], values=['math score', 'reading score', 'writing score'], aggfunc='mean')

                           math score  reading score  writing score
gender education
female associate's degree   65.250000      74.120690      74.000000
       bachelor's degree    68.349206      77.285714      78.380952
       high school          59.351064      68.202128      66.691489
       master's degree      66.500000      76.805556      77.638889
       some college         65.406780      73.550847      74.050847
       some high school     59.296703      69.109890      68.285714
male   associate's degree   70.764151      67.433962      65.405660
       bachelor's degree    70.581818      68.090909      67.654545
       high school          64.705882      61.480392      58.539216
       master's degree      74.826087      73.130435      72.608696
       some college         69.009259      64.990741      63.148148
       some high school     67.840909      64.693182      61.375000

#### Задание 14. Сколько студентов успешно сдали экзамен по математике?

Создайте новый столбец в таблице df под названием Math_PassStatus и запишите в него F, если студент не сдал экзамен по математике (балл за экзамен < passmark), и P иначе.

Посчитайте количество студентов, сдавших и не сдавших экзамен по математике.

Сделайте аналогичные шаги для экзаменов по чтению и письму.

In [75]:
df['Math_PassStatus'] = df['math score'].apply(lambda x: 'F' if x < passmark else 'P')
df['Math_PassStatus'].value_counts()

P    865
F    135
Name: Math_PassStatus, dtype: int64

In [76]:
df['Reading_PassStatus'] = df['reading score'].apply(lambda x: 'F' if x < passmark else 'P')
df['Reading_PassStatus'].value_counts()

P    910
F     90
Name: Reading_PassStatus, dtype: int64

In [77]:
df['Writing_PassStatus'] = df['writing score'].apply(lambda x: 'F' if x < passmark else 'P')
df['Writing_PassStatus'].value_counts()

P    886
F    114
Name: Writing_PassStatus, dtype: int64

#### Задание 15. Сколько студентов успешно сдали все экзамены?

Создайте столбец OverAll_PassStatus и запишите в него для каждого студента 'F', если студент не сдал хотя бы один из трех экзаменов, а иначе 'P'.

Посчитайте количество студентов, которые сдали все экзамены.

In [78]:
df['OverAll_PassStatus'] = ((df['Math_PassStatus'] == 'P') & (df['Reading_PassStatus'] == 'P') & (df['Writing_PassStatus'] == 'P')).apply(lambda x: 'P' if x == True else 'F')
(df['OverAll_PassStatus'] == 'P').sum()

812

#### Задание 16. Переведем баллы в оценки

### Система перевода баллов в оценки
####    больше 90 = A
####      80-90 = B
####      70-80 = C
####      60-70 = D
####      50-60 = E
####    меньше 50 = F (Fail)

Создайте вспомогательную функцию, которая будет по среднему баллу за три экзамена выставлять оценку студенту по данным выше критериям.

Создайте столбец Grade и запишите в него оценку каждого студента.

Выведите количество студентов, получивших каждую из оценок.

**В случае, если средний балл попадает на границу между оценками (т.е. равен ровно 60, 70 или 80 баллов), вы можете интерпретировать условие на своё усмотрение (т.е. можете поставить за 60 баллов оценку D, а можете - E).**

In [79]:
def GetGrade(average_mark):
    if average_mark > 90:
        return 'A'
    elif 80 <= average_mark <= 90:
        return 'B'
    elif 70 <= average_mark < 80:
        return 'C'
    elif 60 <= average_mark < 70:
        return 'D'
    elif 50 <= average_mark < 60:
        return 'E'
    else:
        return 'F'

In [80]:
# Создание столбца Grade и добавление в него новой характеристики average_mark путем передачи в функцию GetGrade среднего значения оценок построчно
df['Grade'] = df[['math score', 'reading score', 'writing score']].mean(axis=1).apply(GetGrade)

In [81]:
df['Grade'].value_counts()

C    261
D    256
E    182
B    148
F    103
A     50
Name: Grade, dtype: int64